# Generated by Django 2.0.13 on 2019-09-04 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meuser',
            name='DD',
            field=models.IntegerField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='meuser',
            name='MM',
            field=models.IntegerField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='meuser',
            name='YY',
            field=models.IntegerField(max_length=2, null=True),
        ),
    ]
