# Generated by Django 2.0.13 on 2019-09-04 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190904_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meuser',
            name='YY',
            field=models.IntegerField(max_length=4, null=True),
        ),
    ]
