# Generated by Django 2.0.13 on 2019-09-04 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190904_0251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meuser',
            old_name='YY',
            new_name='YYYY',
        ),
    ]
